FROM sickcodes/docker-osx:latest

RUN NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

RUN eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" && \
    brew install chezmoi fish starship

ENV PATH="/home/linuxbrew/.linuxbrew/bin:${PATH}"

ENTRYPOINT [ "/bin/bash" ]